# Generated by Django 6.0.7 on 2026-07-26 01:33

import django.utils.timezone
import shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guideId', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('timestamp', shipments.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('updatedBy', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'StatusHistory',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trackingNumber', models.CharField(max_length=15)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('createdAt', models.DateField(default=django.utils.timezone.now)),
                ('updatedAt', shipments.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('currentStatus', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Guide',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('createdAt', models.DateField(default=django.utils.timezone.now)),
                ('updatedAt', shipments.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
