# Generated by Django 6.0.7 on 2026-07-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_address', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_address', models.CharField(max_length=255)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_status', models.CharField(choices=[('created', 'Creado'), ('picked_up', 'Recolectado'), ('in_transit', 'En tránsito'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado'), ('failed_attempt', 'Intento fallido'), ('returned', 'Devuelto'), ('cancelled', 'Cancelado')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Creado'), ('picked_up', 'Recolectado'), ('in_transit', 'En tránsito'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado'), ('failed_attempt', 'Intento fallido'), ('returned', 'Devuelto'), ('cancelled', 'Cancelado')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
